version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
      - MYSQL_ROOT_HOST=%

    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app-kaddem:
    depends_on:
      - mysqldb
    image: yassin916/kaddem:0.0.7
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username": "root",
              "spring.datasource.password": "root",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto": "update"
            }'
    stdin_open: true
    tty: true

volumes:
  db: