version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Root password for MySQL
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db:/var/lib/mysql  # Persist data

  app-kaddem:
    depends_on:
      - mysqldb  # Ensure MySQL starts before the app
    image: yassin916/kaddem:0.0.7  # Your application image
    restart: on-failure
    ports:
      - "8089:8089"  # Expose application port
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:  # Volume for MySQL data persistence
